### PR TITLE
fix #61, Log response headers

### LINKED ISSUE #61: error code is not visible
I'm getting this:

```
error: Invalid response code #503 at GET https://api.zerocracy.com:443/exists/faketjxxxiioilaineog, most probably it's an internal error on the server (nil), please report this to https://github.com/zerocracy/baza.rb
/usr/local/bundle/gems/baza.rb-0.4.0/lib/baza-rb.rb:797:in 'BazaRb#checked': Invalid response code #503 at GET https://api.zerocracy.com:443/exists/faketjxxxiioilaineog, most probably it's an internal error on the server (nil), please report this to https://github.com/zerocracy/baza.rb (BazaRb::ServerFailure)
	from /usr/local/bundle/gems/baza.rb-0.4.0/lib/baza-rb.rb:355:in 'block (2 levels) in BazaRb#name_exists?'
	from /usr/local/bundle/gems/retries-0.0.5/lib/retries.rb:46:in 'Kernel#with_retries'
	from /usr/local/bundle/gems/baza.rb-0.4.0/lib/baza-rb.rb:354:in 'block in BazaRb#name_exists?'
	from /usr/local/bundle/gems/elapsed-0.0.1/lib/elapsed.rb:45:in 'Object#elapsed'
	from /usr/local/bundle/gems/baza.rb-0.4.0/lib/baza-rb.rb:352:in 'BazaRb#name_exists?'
	from /usr/local/bundle/gems/judges-0.42.0/lib/judges/commands/pull.rb:41:in 'block in Judges::Pull#run'
	from /usr/local/bundle/gems/elapsed-0.0.1/lib/elapsed.rb:45:in 'Object#elapsed'
	from /usr/local/bundle/gems/judges-0.42.0/lib/judges/commands/pull.rb:40:in 'Judges::Pull#run'
	from /usr/local/bundle/gems/judges-0.42.0/bin/judges:25:in 'block in JudgesGLI.run_it'
	from /usr/local/bundle/gems/gli-2.22.2/lib/gli/command_support.rb:131:in 'GLI::CommandSupport#execute'
	from /usr/local/bundle/gems/gli-2.22.2/lib/gli/app_support.rb:298:in 'block in GLI::AppSupport#call_command'
	from /usr/local/bundle/gems/gli-2.22.2/lib/gli/app_support.rb:311:in 'GLI::AppSupport#call_command'
	from /usr/local/bundle/gems/gli-2.22.2/lib/gli/app_support.rb:85:in 'GLI::AppSupport#run'
	from /usr/local/bundle/gems/judges-0.42.0/bin/judges:209:in '<top (required)>'
	from /usr/local/bundle/bin/judges:25:in 'Kernel#load'
	from /usr/local/bundle/bin/judges:25:in '<main>'
D: GET https://api.zerocracy.com:443/exists/faketjxxxiioilaineog -> 503 (30.07s)
     Connection: close
     Server: Cowboy
     Date: Mon, 05 May 2025 19:50:32 GMT
     Content-Length: 506
     Report-To: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1746474603&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=S%2BT7Oe5%2BG1exqRTrIl63sgW48OMCwR0dqaOSn0yluM0%3D"}]}
     Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1746474603&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=S%2BT7Oe5%2BG1exqRTrIl63sgW48OMCwR0dqaOSn0yluM0%3D
     Nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}
     Content-Type: text/html; charset=utf-8
     Cache-Control: no-cache, no-store
E: Invalid response code #503 at GET https://api.zerocracy.com:443/exists/faketjxxxiioilaineog, most probably it's an internal error on the server (nil), please report this to https://github.com/zerocracy/baza.rb

```

I don't see the value of the `X-Zerocracy-Failure` and `X-Zerocracy-FailureMark` HTTP headers. We should print all response headers (as we do for the request headers) and also embed the values of these two headers into the exception message (if they are present in the response).

### PR DESCRIPTION
**Pull request by paveltrty**
Add X-Zerocracy-Failure and X-Zerocracy-FailureMark to error messages

## Summary by CodeRabbit

* **Bug Fixes**
  * Error logging now conditionally shows response headers (or a "(no headers returned)" note) and appends consolidated failure details from server-response headers; 500 and 503 now share unified guidance in error messages.

* **Tests**
  * Updated tests to assert error messages include failure metadata from response headers.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: lib/baza-rb.rb [hunk 1]
```diff
@@ -696,41 +696,50 @@ def checked(ret, allowed = [200])
...
+
     log = "#{mtd} #{url} -> #{ret.code} (#{format('%0.2f', ret.total_time)}s)"
+
     if allowed.include?(ret.code)
       @loog.debug(log)
       return ret
     end
-    @loog.debug("#{log}\n  #{(ret.headers || {}).map { |k, v| "#{k}: #{v}" }.join("\n  ")}")
+
+    # Log **all response headers**
```
Comment (yegor256) [inline lib/baza-rb.rb]: @paveltrty we don't use empty lines inside method bodies and we also don't use comments

**Comment by yegor256** [comment]
@paveltrty how do we know this new functionality works? We need to add a test.

File: lib/baza-rb.rb [hunk 2]
```diff
@@ -706,30 +706,29 @@ def checked(ret, allowed = [200])
...
     end
-    @loog.debug("#{log}\n  #{(ret.headers || {}).map { |k, v| "#{k}: #{v}" }.join("\n  ")}")
     headers = ret.headers || {}
-    msg = [
-      "Invalid response code ##{ret.code} ",
-      "at #{mtd} #{url}",
-      headers['X-Zerocracy-Flash'] ? " (#{headers['X-Zerocracy-Flash'].inspect})" : ''
-    ].join
+    if headers.any?
+      headers_log = headers.map { |k, v| "  #{k}: #{v}" }.join("\n")
```
Comment (yegor256) [inline lib/baza-rb.rb]: @paveltrty read this: https://www.yegor256.com/2015/01/12/compound-name-is-code-smell.html

File: lib/baza-rb.rb [hunk 3]
```diff
@@ -706,30 +706,29 @@ def checked(ret, allowed = [200])
...
+      @loog.debug("#{log}\n#{headers_log}")
+      @loog.error("#{log}\n#{headers_log}")
+    else
+      @loog.debug("#{log}\n  (no headers returned)")
+      @loog.error("#{log}\n  (no headers returned)")
```
Comment (yegor256) [inline lib/baza-rb.rb]: @paveltrty just `.error()` is enough

File: lib/baza-rb.rb [hunk 4]
```diff
@@ -706,30 +706,29 @@ def checked(ret, allowed = [200])
...
+    end
+    info = []
+    info << "X-Zerocracy-Failure=#{headers['X-Zerocracy-Failure'].inspect}" if headers['X-Zerocracy-Failure']
+    if headers['X-Zerocracy-FailureMark']
+      info << "X-Zerocracy-FailureMark=#{headers['X-Zerocracy-FailureMark'].inspect}"
```
Comment (yegor256) [inline lib/baza-rb.rb]: @paveltrty this will make log line look pretty ugly. let's try to do better formatting.

**Comment by paveltrty** [comment]
@yegor256, check please
